- name: Playbook for setting hardening parameters for Ansible 
  hosts: all
  become: yes

  tasks: 
  - name: Configure password length requirement 
    template: 
      src: pwquality.conf.j2
      dest: /etc/security/pwquality.conf
