- name: Configure Web servers 
  hosts: backends 
  tasks: 
  - name: Install httpd server
    yum: 
      name: httpd 
      state: latest
  
  - name: Start required services 
    service: 
      name: "{{ item }}" 
      state: started
      enabled: true
    with_items:
      - firewalld 
      - httpd
  
  - name: Configure firewalld 
    firewalld:
      service: http
      state: enabled
      permanent: true  
      immediate: true

  - name: Deploy web content
    copy: 
      src: "files/webcontent/{{ content }}/{{item}}"
      dest: /var/www/html
    with_items: 
      - index.html
      - index_fichiers

  - name: Install Haproxy server
    yum:
      name: haproxy
      state: latest

  - name: Start Haproxy Service
    service:
      name: haproxy
      state: started
      enabled: true

  - name: Configure Haproxy
    template:
      dest: /etc/haproxy/haproxy.cfg
      src: templates/haproxy.cfg.j2
    notify: restart_lb
      
  handlers:
  - name: restart_lb
    service: 
      name: haproxy
      state: restarted
