- name: Install package on Windows Managed Host
  hosts: all
  gather_facts: no
  #ignore_errors: yes 
  
  tasks:
  - name: Install Remote Desktop Connection Manager from msi
    win_package:
      path: https://download.microsoft.com/download/A/F/0/AF0071F3-B198-4A35-AA90-C68D103BDCCF/rdcman.msi
      product_id: '{0240359E-6A4C-4884-9E94-B397A02D893C}'
      state: present
    tags:
    - install

  - name: Uninstall Remote Desktop Connection Manager
    win_package:
      product_id: '{0240359E-6A4C-4884-9E94-B397A02D893C}'
      state: absent
    tags:
    - rollback
